---
platform: linux

image_resource:
  type: docker-image
  source: {repository: jigsheth57/pcfworkshop}

inputs:
  - name: lab-repo

outputs:
  - name: build-artifact

run:
  path: lab-repo/lab1/ci/tasks/unit-test.sh
